# Generated by Django 2.1.3 on 2018-11-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0004_auto_20181124_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='topics',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='topic_vector',
            field=models.FileField(null=True, upload_to='topic_vector/'),
        ),
    ]
