# Generated by Django 2.1.3 on 2018-12-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0006_topic_real_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='topic_vector',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interest_vector',
            field=models.FileField(null=True, upload_to='interest_vector/'),
        ),
    ]
