# Generated by Django 2.1.3 on 2018-12-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0007_auto_20181201_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videohistory',
            name='video',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='topics',
            field=models.ManyToManyField(to='data_manager.Topic'),
        ),
        migrations.AddField(
            model_name='videohistory',
            name='video_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
