# Generated by Django 2.1.3 on 2018-12-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0008_auto_20181201_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='areas',
            field=models.ManyToManyField(to='data_manager.Area'),
        ),
    ]
