# Generated by Django 2.1.3 on 2018-12-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0009_userprofile_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
